# Generated by Django 2.0.7 on 2018-07-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pop',
            old_name='dnsname',
            new_name='vlans',
        ),
    ]
