# Generated by Django 2.0.7 on 2018-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20180709_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='bandwidth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='comments',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='contacts',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='manager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='vlans',
            field=models.CharField(max_length=100),
        ),
    ]
