# Generated by Django 2.0.7 on 2018-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180709_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pop',
            name='upstream',
            field=models.ManyToManyField(to='inventory.Core'),
        ),
    ]
