# Generated by Django 2.0.7 on 2018-07-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180711_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='downstream',
            field=models.ManyToManyField(to='inventory.Pop'),
        ),
    ]
