# Generated by Django 2.0.7 on 2018-07-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_core_downstream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='downstream',
        ),
    ]
