# Generated by Django 2.0.7 on 2018-07-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_core_downstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='downstream',
            field=models.ManyToManyField(to='inventory.Pop'),
        ),
    ]
