# Generated by Django 2.0.7 on 2018-07-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180724_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='downstream',
            field=models.ManyToManyField(blank=True, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='upstream',
            field=models.ManyToManyField(blank=True, to='inventory.Core'),
        ),
    ]
