# Generated by Django 2.0.7 on 2018-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180724_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('vlans', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
    ]
