# Generated by Django 2.0.7 on 2018-07-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180731_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vlans',
            field=models.CharField(default=555, max_length=100),
            preserve_default=False,
        ),
    ]
