# Generated by Django 2.0.7 on 2018-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_customer_vlans'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='switch',
            field=models.CharField(default=666, max_length=100),
            preserve_default=False,
        ),
    ]
