# Generated by Django 2.0.7 on 2018-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_customer_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('dnsname', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=100)),
            ],
        ),
    ]
