# Generated by Django 2.0.7 on 2018-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='pop',
            name='devices',
            field=models.ManyToManyField(blank=True, to='inventory.Device'),
        ),
    ]
