# Generated by Django 2.0.7 on 2018-08-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_pop_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='address',
            field=models.ManyToManyField(blank='True', to='inventory.Pop'),
        ),
    ]
