# Generated by Django 2.0.7 on 2018-08-28 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_device_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='geoaddress',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
