# Generated by Django 2.0.7 on 2018-08-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_device_geoaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='devices',
            field=models.ManyToManyField(blank=True, to='inventory.Device'),
        ),
    ]
