# Generated by Django 2.0.7 on 2018-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_core_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='coreaddress',
            field=models.ManyToManyField(blank='True', to='inventory.Core'),
        ),
    ]
