# Generated by Django 2.0.7 on 2018-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_device_coreaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
