# Generated by Django 2.0.7 on 2018-08-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20180829_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
