# Generated by Django 2.0.7 on 2018-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20180829_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pop',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
