# Generated by Django 2.0.7 on 2018-08-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20180829_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
