# Generated by Django 2.0.7 on 2018-09-06 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20180906_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('A', 'Your string should contain letter A in it.')]),
        ),
    ]
