# Generated by Django 2.0.7 on 2018-09-06 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20180906_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$', 'Your string should contain letter A in it.')]),
        ),
    ]
