# Generated by Django 2.0.7 on 2018-09-06 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20180906_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$')]),
        ),
    ]
