# Generated by Django 2.0.7 on 2018-09-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20180906_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
