# Generated by Django 2.0.7 on 2018-09-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20180907_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='contacts',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
