# Generated by Django 2.0.7 on 2018-09-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_network_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='tocore',
            field=models.ForeignKey(blank=True, default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='inventory.Core'),
        ),
        migrations.AddField(
            model_name='network',
            name='tocustomer',
            field=models.ForeignKey(blank=True, default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='inventory.Customer'),
        ),
        migrations.AddField(
            model_name='network',
            name='topop',
            field=models.ForeignKey(blank=True, default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='network',
            name='comment',
            field=models.CharField(blank=True, default='SOME STRING', max_length=100),
        ),
    ]
