# Generated by Django 2.0.7 on 2018-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_auto_20180910_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
