# Generated by Django 2.0.7 on 2018-09-10 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_auto_20180910_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$')])),
                ('status', models.CharField(choices=[('FREE', 'Свободно'), ('BUSY', 'Занято')], default='FREE', max_length=4)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
