# Generated by Django 2.0.7 on 2018-09-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_auto_20180910_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='tocore',
        ),
        migrations.RemoveField(
            model_name='network',
            name='tocustomer',
        ),
        migrations.RemoveField(
            model_name='network',
            name='topop',
        ),
    ]
