# Generated by Django 2.0.7 on 2018-09-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0048_auto_20180910_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='core',
            new_name='tocore',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='customer',
            new_name='tocustomer',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='pop',
            new_name='topop',
        ),
    ]
