# Generated by Django 2.0.7 on 2018-09-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_auto_20180910_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='segment',
            field=models.CharField(choices=[('FREE', 'Свободно'), ('BUSY', 'Занято')], max_length=9, null=True),
        ),
    ]
