# Generated by Django 2.0.7 on 2018-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_network_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='segment',
            field=models.CharField(choices=[('MPLS', 'MPLS'), ('CORE', 'CORE'), ('Customers', 'CUSTOMER')], max_length=9, null=True),
        ),
    ]
