# Generated by Django 2.0.7 on 2018-09-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0051_auto_20180912_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='segment',
            field=models.CharField(choices=[('MPLS', 'MPLS'), ('CORE', 'CORE'), ('Customers', 'CUSTOMERS')], max_length=9, null=True),
        ),
    ]
