# Generated by Django 2.0.7 on 2018-09-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_auto_20180912_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='segment',
            field=models.CharField(choices=[('TECH', 'TECH'), ('MPLS', 'MPLS'), ('CORE', 'CORE'), ('Customers', 'CUSTOMERS')], max_length=9, null=True),
        ),
    ]
