# Generated by Django 2.0.7 on 2018-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_pop_otherpopsdownstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='core',
            name='contacts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='core',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='core',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='core',
            name='vlans',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contacts',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='switch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vlans',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.ManyToManyField(blank=True, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='device',
            name='coreaddress',
            field=models.ManyToManyField(blank=True, to='inventory.Core'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pop',
            name='vlans',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
