# Generated by Django 2.0.7 on 2018-10-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_auto_20181013_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='devices',
            field=models.ManyToManyField(blank=True, to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='core',
            name='downstream',
            field=models.ManyToManyField(blank=True, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='upstream',
            field=models.ManyToManyField(blank=True, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='device',
            name='address',
            field=models.ManyToManyField(blank=True, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='device',
            name='coreaddress',
            field=models.ManyToManyField(blank=True, to='inventory.Core'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='devices',
            field=models.ManyToManyField(blank=True, to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='downstream',
            field=models.ManyToManyField(blank=True, to='inventory.Customer'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='otherpopsdownstream',
            field=models.ManyToManyField(blank=True, to='inventory.Pop'),
        ),
        migrations.AlterField(
            model_name='pop',
            name='upstream',
            field=models.ManyToManyField(blank=True, to='inventory.Core'),
        ),
    ]
