# Generated by Django 2.0.7 on 2020-11-02 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0010_auto_20201102_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^([0-9]{1,3}\\.){3}[0-9]{1,3}(\\/([0-9]|[1-2][0-9]|3[0-2]))?$')])),
                ('status', models.CharField(choices=[('FREE', 'Свободно'), ('BUSY', 'Занято')], default='FREE', max_length=4)),
                ('segment', models.CharField(choices=[('TECH', 'TECH'), ('MPLS', 'MPLS'), ('CORE', 'CORE'), ('Customers', 'CUSTOMERS')], max_length=9)),
                ('comment', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True, max_length=1000)),
                ('tocore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Core')),
                ('tocustomer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Customer')),
                ('topop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Pop')),
            ],
        ),
    ]
