# Generated by Django 2.0.7 on 2019-04-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20190416_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2vpn',
            name='pointA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.Pop'),
        ),
    ]
