# Generated by Django 2.0.7 on 2019-04-23 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_device_geoaddress'),
        ('channels', '0005_auto_20190423_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='l2vpn',
            name='pointA',
        ),
        migrations.AddField(
            model_name='l2vpn',
            name='pointA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpn_pointA', to='inventory.Pop'),
        ),
        migrations.RemoveField(
            model_name='l2vpn',
            name='pointB',
        ),
        migrations.AddField(
            model_name='l2vpn',
            name='pointB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpn_pointB', to='inventory.Pop'),
        ),
    ]
