# Generated by Django 2.0.7 on 2019-04-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_device_geoaddress'),
        ('channels', '0006_auto_20190423_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vpn',
            name='coreA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpn_coreA', to='inventory.Core'),
        ),
        migrations.AddField(
            model_name='l2vpn',
            name='coreB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpn_coreB', to='inventory.Core'),
        ),
    ]
