# Generated by Django 2.0.7 on 2019-04-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_device_geoaddress'),
        ('channels', '0007_auto_20190423_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vpn',
            name='deviceA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpn_deviceA', to='inventory.Device'),
        ),
        migrations.AddField(
            model_name='l2vpn',
            name='deviceB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='l2vpn_deviceB', to='inventory.Device'),
        ),
    ]
