# Generated by Django 2.0.7 on 2019-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0008_auto_20190429_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vpn',
            name='portA',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='l2vpn',
            name='portB',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
