# Generated by Django 2.0.7 on 2019-05-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_auto_20190429_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='l2vpn',
            name='vlan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True),
        ),
    ]
