# Generated by Django 2.0.7 on 2019-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_l2vpn_vlan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2vpn',
            name='vlan',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
