# Generated by Django 2.0.7 on 2019-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_auto_20190527_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2vpn',
            name='portA',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='l2vpn',
            name='portB',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
